### ISSUE TITLE
The integer for "day" must be quoted

### ISSUE THREAD

**Issue by FlipperPA** [meeting-guide/react#4] opened 2019-03-17 15:02 UTC
Currently, the Meeting Guide JSON spec says to use an unquoted integer for the "day" field: https://github.com/meeting-guide/spec

However, if using an unquoted integer, "Sunday" doesn't appear. This can be fixed by quoting the integer; putting `"day": "0"` instead of `"day": 0`.

**Comment by mathteacher** [comment] 2019-06-27 11:14
I just noticed this issue. I also found this bug when I was working on the Google Sheet support. It is now fixed by checking if the day is an integer (line 186 in app.jsx) and converting it to a string if so. I figured out the issue is because meeting.day will evaluate to false for Sunday since it's equal to 0 which causes issues in several places in the app; therefore, the easiest fix was just to change it to a string during the data processing.

**Comment by joshreisner** [comment] 2019-06-28 21:13
Thanks @mathteacher for fixing

**Closed by joshreisner** 2019-06-28 21:13 UTC
Labels: bug
